# Generated by Django 5.0.1 on 2024-01-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_deletedinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedinvestment',
            name='investment',
        ),
        migrations.AddField(
            model_name='deletedinvestment',
            name='investment_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deletedinvestment',
            name='symbol_d',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='investments.asset', to_field='symbol'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
