# Generated by Django 5.0.1 on 2024-01-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_deletedinvestment_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedinvestment',
            name='investment_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
