# Generated by Django 5.0.1 on 2024-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_deletedinvestment_investment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedinvestment',
            name='date_bought',
            field=models.DateField(default='2000-1-1'),
        ),
        migrations.AddField(
            model_name='deletedinvestment',
            name='price_bought',
            field=models.FloatField(default=0.0),
        ),
    ]
