# Generated by Django 5.0.1 on 2024-01-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_deletedinvestment_date_bought_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteUsersAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('symbol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='investments.asset')),
            ],
        ),
    ]
